name: Sync Labels

on:
  schedule:
  # once a day at midnight
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-labels:
    uses: shipyard/meta/.github/workflows/sync-labels.yml@main
    with:
        categories: status,aws,semver
    secrets:
      github-token: ${{ secrets.PRO_ACCESS_TOKEN }}
